name: Build Local Docker utilizando o Docker Compose

on:
  push:
    branches: [ "master", "desenv" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Limpar imagens antigas
        run: docker image prune -f

      - name: Definir Variáveis de Ambiente
        run: |
          if ("${{ github.ref }}" -like "*master*") {
            echo "ENV_FILE=docker-compose.yml" >> $GITHUB_ENV
            echo "PORTA_API=5000" >> $GITHUB_ENV
          } else {
            echo "ENV_FILE=docker-compose-dsv.yml" >> $GITHUB_ENV
            echo "PORTA_API=5001" >> $GITHUB_ENV
          }
          
       - name: Debug das Variáveis
        run: |
          echo "O arquivo usado será: ${{ env.ENV_FILE }}"
          echo "A porta usada será: ${{ env.PORTA_API }}"

      - name: Parar containers e libertar porta
        continue-on-error: true
        run: |
          docker-compose -f ${{ env.ENV_FILE }} down --remove-orphans
          # O comando abaixo tenta libertar a porta apenas se necessário
          $conn = Get-NetTCPConnection -LocalPort ${{ env.PORTA_API }} -ErrorAction SilentlyContinue
          if ($conn) {
              Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue | Stop-Process -Force
          }

      - name: Build Limpo e Deploy
        run: |
          docker-compose -f ${{ env.ENV_FILE }} build --no-cache
          docker-compose -f ${{ env.ENV_FILE }} up -d