name: Build Local Docker utilizando o Docker Compose

on:
  push:
    branches: [ "master", "desenv" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Limpar imagens antigas
        run: docker image prune -f

      - name: Definir Variáveis de Ambiente
        run: |
          if ("${{ github.ref }}" -like "*master*") {
            Add-Content -Path $env:GITHUB_ENV -Value "ENV_FILE=docker-compose.yml"
            Add-Content -Path $env:GITHUB_ENV -Value "PORTA_API=5000"
          } else {
            Add-Content -Path $env:GITHUB_ENV -Value "ENV_FILE=docker-compose-dsv.yml"
            Add-Content -Path $env:GITHUB_ENV -Value "PORTA_API=5001"
          }
          
      - name: Debug das Variáveis
        run: |
          echo "O arquivo usado: ${{ env.ENV_FILE }}"
          echo "A porta usada: ${{ env.PORTA_API }}"

      - name: Parar containers e libertar porta
        continue-on-error: true
        run: |
          docker-compose -f ${{ env.ENV_FILE }} down --remove-orphans
          # O comando abaixo tenta libertar a porta apenas se necessário
          $conn = Get-NetTCPConnection -LocalPort ${{ env.PORTA_API }} -ErrorAction SilentlyContinue
          if ($conn) {
              Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue | Stop-Process -Force
          }

      - name: Build Limpo e Deploy
        run: |
          docker-compose -f ${{ env.ENV_FILE }} build --no-cache
          docker-compose -f ${{ env.ENV_FILE }} up -d